### ISSUE TITLE
Example: Learning NumericalMarkowitz parameters

### ISSUE THREAD

**Issue by jankrepl** [jankrepl/deepdow#31]
Would be nice to show, how `deepdow` is able to directly learn or have a network predictor of any input variables of the `deepdow.layers.NumericalMarkowitz`

It might be a good idea to use real data (i.e. `yfinance`), however one needs to be careful about the example running too long (both CI and readthedocs need to run it)

**Comment by robertmartin8** [comment]
For any code that needs to be run by CI, testing, etc, I really wouldn't recommend calling `yfinance` live. Better to download the data manually and save it to a `resources` folder. `yfinance` sometimes goes down unpredictably (but is generally very good)

**Comment by jankrepl** [comment]
@robertmartin8 Thanks for the tip.

Personally, I am just afraid of pushing a lot of binary files to the github repository. Who knows, maybe in a couple of weeks we realize that the dataset was not the right one.
