### ISSUE TITLE
Extra linefeed in Epoch reporting

### ISSUE THREAD

**Issue by gmgreg** [jankrepl/deepdow#74]
With each epoch there is an extra linefeed inserted when reporting metrics in Jupyter.  E.g. notice in the below screenshot the gap between each line.  It grows again in epoch 3 and so on.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/853223/97456407-1481bb80-18f6-11eb-9f3b-37577293aed7.png">

**Comment by jankrepl** [comment]
Nice find! Definitely something to be fixed. I will try to check the source code and post an update.

I actually never run `deepdow` from a jupyter notebook. Instead, I launch it as a python script and there the progress bar works ok. Note that all the documentation examples can also be download as python scripts if you are interested.

**Comment by gmgreg** [comment]
While learning how deepdow works and iterating frequently it's a bit easier to use Jupyter.  Once I can build models and understand how the layers interact I'll use python scripts directly. 

The bug noted is minor - just thought I'd call it out while it was top of mind.
