### ISSUE TITLE
Short positions

### ISSUE THREAD

**Issue by gmgreg** [jankrepl/deepdow#76]
Looking at the [allocation layer documentation ](https://deepdow.readthedocs.io/en/latest/source/layers.html#allocation-layers) and not seeing how to handle short positions.  E.g. if one was looking to create a market neutral portfolio equal weighted with long and short how might this be modeled?

**Comment by jankrepl** [comment]
You are right that currently all the implemented allocation layers are long only. 

I guess the simplest way to allow for short positions is to drop the `w_i > 0` constraints in `NumericalMarkowitz` - this would require slightly modifying the source code around [this line](https://github.com/jankrepl/deepdow/blob/ea894c590d41f1c0ce93679811c11c90e0f74549/deepdow/layers/allocate.py#L199).

In general, you can write your own `nn.Module` that takes in some input tensor `x` and spits out the weight allocation over all assets. As long as the weights sum up to one, all the `deepdow` machinery should work.

**Comment by jankrepl** [comment]
I am going to close this issue because of inactivity. Feel free to reopen!
